version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Caminho para o diretório do backend
      dockerfile: Dockerfile  # Se o Dockerfile tiver um nome diferente, ajuste aqui
    container_name: backend-container
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/react-mongodb  # Configuração do URI para o MongoDB
    depends_on:
      - mongo  # Garante que o MongoDB seja iniciado antes do backend
    networks:
      - app-network

  frontend:
    build:
      context: ./front  # Caminho para o diretório do frontend
      dockerfile: Dockerfile  # Nome do Dockerfile do frontend, se for o padrão, pode omitir
    container_name: frontend-container
    ports:
      - "3000:3000"  # Porta exposta para o frontend React
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
